repositories:
- name: "mocaccino-micro"
  url: "https://get.mocaccino.org/mocaccino-micro"
- name: "mocaccino-extra"
  url: "https://get.mocaccino.org/mocaccino-extra"
- name: "mocaccino-portage-tree"
  url: "https://get.mocaccino.org/mocaccino-portage-tree"
- name: "luet-official"
  url: "https://raw.githubusercontent.com/Luet-lab/luet-repo/gh-pages"
- name: "livecd"
  url: "https://raw.githubusercontent.com/Luet-lab/livecd-specs/gh-pages"
- name: "kernel"
  url: "https://get.mocaccino.org/mocaccino-kernel"